from __future__ import annotations

from pathlib import Path
import re
import typer


def _sanitize_module_name(project_name: str) -> str:
    """
    Convert a project name to a valid Python module name.

    Examples:
      my-project -> my_project
      my project -> my_project
    """
    name = project_name.lower()
    name = re.sub(r"[^a-z0-9_]", "_", name)
    if not name[0].isalpha():
        name = f"project_{name}"
    return name


def scaffold_project(project_name: str) -> None:
    project_dir = Path(project_name)

    # ============================
    # VALIDATIONS (filesystem-level)
    # ============================
    if project_dir.exists():
        raise FileExistsError(f"Directory '{project_name}' already exists.")

    if not project_name.strip():
        raise ValueError("Project name cannot be empty.")

    # ============================
    # CREATE DIRECTORIES
    # ============================
    actors_dir = project_dir / "my_actors"
    workflows_dir = project_dir / "workflows"
    tests_dir = project_dir / "tests"

    actors_dir.mkdir(parents=True)
    workflows_dir.mkdir(parents=True)
    tests_dir.mkdir(parents=True)

    # ============================
    # __init__.py FILES
    # ============================
    for d in (actors_dir, workflows_dir, tests_dir):
        (d / "__init__.py").write_text("", encoding="utf-8")

    # ============================
    # SAMPLE ACTOR (tool-based)
    # ============================
    actor_lines = [
        "from framework.actor.base_actor import Actor\n",
        "from framework.types import ToolContract\n",
        "\n",
        "class SampleActor(Actor):\n",
        '    """Minimal sample actor generated by JAF CLI."""\n',
        "\n",
        '    name = "sample_actor"\n',
        "\n",
        "    def configure(self) -> None:\n",
        "        # Register tools\n",
        "        self.tools = [self.hello_tool]\n",
        "\n",
        "    @ToolContract(output=dict)\n",
        '    def hello_tool(self, name: str = "world") -> dict:\n',
        '        return {"message": f"Hello, {name}!"}\n',
    ]

    with (actors_dir / "sample_actor.py").open(
        "w", encoding="utf-8", newline="\n"
    ) as f:
        f.writelines(actor_lines)

    # ============================
    # SAMPLE WORKFLOW (illustrative)
    # ============================
    workflow_lines = [
        "from my_actors.sample_actor import SampleActor\n",
        "\n",
        "def build_workflow():\n",
        '    """Example workflow factory."""\n',
        "    return [SampleActor()]\n",
    ]

    with (workflows_dir / "sample_workflow.py").open(
        "w", encoding="utf-8", newline="\n"
    ) as f:
        f.writelines(workflow_lines)

    # ============================
    # SAMPLE TEST (engine-based, tool execution)
    # ============================
    test_lines = [
        "import pytest\n",
        "from my_actors.sample_actor import SampleActor\n",
        "from framework.engine.native_engine import NativeEngine\n",
        "from framework.types import PlanStep\n",
        "\n",
        "@pytest.mark.asyncio\n",
        "async def test_sample_actor_tool():\n",
        "    actor = SampleActor()\n",
        "    actor.configure()\n",
        "    engine = NativeEngine()\n",
        '    step = PlanStep(actor_name=actor.name, tool_name="hello_tool", parameters={"name": "JAF"})\n',
        "    context = {actor.name: actor}\n",
        "    result = await engine.execute_step(step, context)\n",
        "    assert result.status == 'success'\n",
        '    assert result.output == {"message": "Hello, JAF!"}\n',
    ]

    with (tests_dir / "test_sample_actor.py").open(
        "w", encoding="utf-8", newline="\n"
    ) as f:
        f.writelines(test_lines)

    # ============================
    # ROOT FILES
    # ============================
    (project_dir / "requirements.txt").write_text(
        "jaf-framework\n",
        encoding="utf-8",
    )

    (project_dir / "README.md").write_text(
        f"""# {project_name}

This project was generated using **JAF CLI**.

## Setup

```bash
pip install -r requirements.txt

```

Structure

my_actors/ → custom actors

workflows/ → workflow definitions

tests/ → pytest tests
""",
        encoding="utf-8",
    )

    (project_dir / ".gitignore").write_text(
        """pycache/
.venv/
.pytest_cache/
.idea/
.vscode/
""",
        encoding="utf-8",
    )

    # ============================
    # SUCCESS MESSAGE
    # ============================
    typer.secho(
        f"\n✅ Project '{project_name}' created at: {project_dir}",
        fg=typer.colors.GREEN,
    )
    typer.echo("\nNext steps:")
    typer.echo(f" cd {project_name}")
    typer.echo(" pip install -r requirements.txt")
    typer.echo(" # Start coding in my_actors/ and workflows/")
